// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgphQJWtUyj0fiRUNu9zTIp3qD3sbEfJw',
    appId: '1:862556238662:web:97811b30b020831d69eb47',
    messagingSenderId: '862556238662',
    projectId: 'agro-robot-control',
    authDomain: 'agro-robot-control.firebaseapp.com',
    storageBucket: 'agro-robot-control.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUozFE34wVbtCZaDeQbK5TZSajscRFRqg',
    appId: '1:862556238662:android:aab996146c69bcc369eb47',
    messagingSenderId: '862556238662',
    projectId: 'agro-robot-control',
    storageBucket: 'agro-robot-control.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgWpTWC2SkBTN-MzVvv260fP8yDYqs6Nw',
    appId: '1:862556238662:ios:c582e675adb2179069eb47',
    messagingSenderId: '862556238662',
    projectId: 'agro-robot-control',
    storageBucket: 'agro-robot-control.firebasestorage.app',
    iosBundleId: 'com.example.agriBotControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgWpTWC2SkBTN-MzVvv260fP8yDYqs6Nw',
    appId: '1:862556238662:ios:c582e675adb2179069eb47',
    messagingSenderId: '862556238662',
    projectId: 'agro-robot-control',
    storageBucket: 'agro-robot-control.firebasestorage.app',
    iosBundleId: 'com.example.agriBotControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgphQJWtUyj0fiRUNu9zTIp3qD3sbEfJw',
    appId: '1:862556238662:web:74e27dfb1fff757069eb47',
    messagingSenderId: '862556238662',
    projectId: 'agro-robot-control',
    authDomain: 'agro-robot-control.firebaseapp.com',
    storageBucket: 'agro-robot-control.firebasestorage.app',
  );

}